version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      SV_HOST: localhost
      SV_PORT: 3333
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: datasane
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: datasane
    volumes:
      - db_data:/var/lib/mysql

  etl-java-api:
    build:
      context: .
      dockerfile: Dockerfile.java
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: datasane
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

volumes:
  db_data: