version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      SV_HOST: localhost
      SV_PORT: 3333
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: datasane
    depends_on:
      - db

  db:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: datasane
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
